// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.urbanairship.ram.demo.proto;

public final class DemoTweet {
  private DemoTweet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    SUBMIT(0, 1),
    ;
    
    public static final int SUBMIT_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static RequestType valueOf(int value) {
      switch (value) {
        case 1: return SUBMIT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.urbanairship.ram.demo.proto.DemoTweet.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final RequestType[] VALUES = {
      SUBMIT, 
    };
    
    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:RequestType)
  }
  
  public interface TweetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string tweetmsg = 1;
    boolean hasTweetmsg();
    String getTweetmsg();
    
    // required int32 tweetid = 2;
    boolean hasTweetid();
    int getTweetid();
  }
  public static final class Tweet extends
      com.google.protobuf.GeneratedMessage
      implements TweetOrBuilder {
    // Use Tweet.newBuilder() to construct.
    private Tweet(Builder builder) {
      super(builder);
    }
    private Tweet(boolean noInit) {}
    
    private static final Tweet defaultInstance;
    public static Tweet getDefaultInstance() {
      return defaultInstance;
    }
    
    public Tweet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.urbanairship.ram.demo.proto.DemoTweet.internal_static_Tweet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.urbanairship.ram.demo.proto.DemoTweet.internal_static_Tweet_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string tweetmsg = 1;
    public static final int TWEETMSG_FIELD_NUMBER = 1;
    private java.lang.Object tweetmsg_;
    public boolean hasTweetmsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTweetmsg() {
      java.lang.Object ref = tweetmsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tweetmsg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTweetmsgBytes() {
      java.lang.Object ref = tweetmsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tweetmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 tweetid = 2;
    public static final int TWEETID_FIELD_NUMBER = 2;
    private int tweetid_;
    public boolean hasTweetid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTweetid() {
      return tweetid_;
    }
    
    private void initFields() {
      tweetmsg_ = "";
      tweetid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTweetmsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTweetid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTweetmsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, tweetid_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTweetmsgBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tweetid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.urbanairship.ram.demo.proto.DemoTweet.Tweet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.urbanairship.ram.demo.proto.DemoTweet.Tweet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.urbanairship.ram.demo.proto.DemoTweet.TweetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.urbanairship.ram.demo.proto.DemoTweet.internal_static_Tweet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.urbanairship.ram.demo.proto.DemoTweet.internal_static_Tweet_fieldAccessorTable;
      }
      
      // Construct using com.urbanairship.ram.demo.proto.DemoTweet.Tweet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        tweetmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tweetid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.urbanairship.ram.demo.proto.DemoTweet.Tweet.getDescriptor();
      }
      
      public com.urbanairship.ram.demo.proto.DemoTweet.Tweet getDefaultInstanceForType() {
        return com.urbanairship.ram.demo.proto.DemoTweet.Tweet.getDefaultInstance();
      }
      
      public com.urbanairship.ram.demo.proto.DemoTweet.Tweet build() {
        com.urbanairship.ram.demo.proto.DemoTweet.Tweet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.urbanairship.ram.demo.proto.DemoTweet.Tweet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.urbanairship.ram.demo.proto.DemoTweet.Tweet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.urbanairship.ram.demo.proto.DemoTweet.Tweet buildPartial() {
        com.urbanairship.ram.demo.proto.DemoTweet.Tweet result = new com.urbanairship.ram.demo.proto.DemoTweet.Tweet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tweetmsg_ = tweetmsg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tweetid_ = tweetid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.urbanairship.ram.demo.proto.DemoTweet.Tweet) {
          return mergeFrom((com.urbanairship.ram.demo.proto.DemoTweet.Tweet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.urbanairship.ram.demo.proto.DemoTweet.Tweet other) {
        if (other == com.urbanairship.ram.demo.proto.DemoTweet.Tweet.getDefaultInstance()) return this;
        if (other.hasTweetmsg()) {
          setTweetmsg(other.getTweetmsg());
        }
        if (other.hasTweetid()) {
          setTweetid(other.getTweetid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTweetmsg()) {
          
          return false;
        }
        if (!hasTweetid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tweetmsg_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tweetid_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string tweetmsg = 1;
      private java.lang.Object tweetmsg_ = "";
      public boolean hasTweetmsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTweetmsg() {
        java.lang.Object ref = tweetmsg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tweetmsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTweetmsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tweetmsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearTweetmsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tweetmsg_ = getDefaultInstance().getTweetmsg();
        onChanged();
        return this;
      }
      void setTweetmsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        tweetmsg_ = value;
        onChanged();
      }
      
      // required int32 tweetid = 2;
      private int tweetid_ ;
      public boolean hasTweetid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTweetid() {
        return tweetid_;
      }
      public Builder setTweetid(int value) {
        bitField0_ |= 0x00000002;
        tweetid_ = value;
        onChanged();
        return this;
      }
      public Builder clearTweetid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tweetid_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Tweet)
    }
    
    static {
      defaultInstance = new Tweet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Tweet)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Tweet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Tweet_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\"*\n\005Tweet\022\020\n\010tweetmsg\030\001 \002(\t\022" +
      "\017\n\007tweetid\030\002 \002(\005*\031\n\013RequestType\022\n\n\006SUBMI" +
      "T\020\001B,\n\037com.urbanairship.ram.demo.protoB\t" +
      "DemoTweet"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Tweet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Tweet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Tweet_descriptor,
              new java.lang.String[] { "Tweetmsg", "Tweetid", },
              com.urbanairship.ram.demo.proto.DemoTweet.Tweet.class,
              com.urbanairship.ram.demo.proto.DemoTweet.Tweet.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
